# Generated by Django 6.0.4 on 2026-06-26 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_nav_branding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='nav_name',
            field=models.CharField(blank=True, help_text='Nome mostrato nella nav e nel titolo della landing (lascia vuoto per usare il nome prodotto).', max_length=120),
        ),
        migrations.AlterField(
            model_name='product',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube o Vimeo — es. https://youtu.be/xxxx. Mostrato nella sezione hero.', verbose_name='URL video'),
        ),
    ]
