# Generated by Django 6.0.4 on 2026-06-13 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_performance_indexes"),
        ("orders", "0004_swap_customer_fk"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["status"], name="orders_orde_status_c6dd84_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["customer", "-created_at"],
                name="orders_orde_custome_413d7d_idx",
            ),
        ),
    ]
