# Generated by Django 5.1.15 on 2026-04-27 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('auth', 'Auth'), ('customer', 'Customer'), ('order', 'Order'), ('invoice', 'Invoice'), ('project', 'Project'), ('task', 'Task'), ('system', 'System')], default='system', max_length=16)),
                ('verb', models.CharField(max_length=64)),
                ('label', models.CharField(max_length=300)),
                ('url', models.CharField(blank=True, max_length=300)),
                ('icon', models.CharField(blank=True, max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='activity_ac_created_90c2a2_idx'), models.Index(fields=['actor', '-created_at'], name='activity_ac_actor_i_6c56ef_idx'), models.Index(fields=['category', '-created_at'], name='activity_ac_categor_87d536_idx')],
            },
        ),
    ]
