# Generated by Django 6.0.4 on 2026-06-13 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["deleted_at"], name="customers_c_deleted_a9584a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["status"], name="customers_c_status_ce44cf_idx"),
        ),
    ]
