# Generated by Django 5.1.15 on 2026-04-29 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_location_user_title_user_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pending_deletion_at',
            field=models.DateTimeField(blank=True, help_text='Set when the user requests deletion; cleared on cancel. A management command performs hard delete after the grace period.', null=True),
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('login', 'Sign in'), ('logout', 'Sign out'), ('login_failed', 'Sign in failed'), ('password_changed', 'Password changed'), ('two_factor_enabled', 'Two-factor enabled'), ('two_factor_disabled', 'Two-factor disabled'), ('api_key_created', 'API key created'), ('api_key_revoked', 'API key revoked'), ('session_revoked', 'Session signed out (other)'), ('data_export_requested', 'Data export requested'), ('account_deletion_requested', 'Account deletion requested'), ('account_deletion_canceled', 'Account deletion canceled')], max_length=40)),
                ('description', models.CharField(blank=True, max_length=400)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=400)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='accounts_au_user_id_adbc45_idx'), models.Index(fields=['kind'], name='accounts_au_kind_49c20c_idx')],
            },
        ),
        migrations.CreateModel(
            name='SessionMetadata',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('user_agent', models.CharField(blank=True, max_length=400)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_metadata', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_seen_at'],
                'indexes': [models.Index(fields=['user', '-last_seen_at'], name='accounts_se_user_id_338f93_idx')],
            },
        ),
    ]
