# Generated by Django 6.0.4 on 2026-06-22 09:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='bookmakers/logos/')),
                ('logo_url', models.URLField(blank=True, help_text='Alternativa al file: URL pubblico del logo.')),
                ('category', models.CharField(choices=[('sport', 'Solo scommesse sportive'), ('casino', 'Solo casinò'), ('both', 'Scommesse + Casinò')], default='both', max_length=10)),
                ('license_type', models.CharField(choices=[('adm', 'ADM (Italia)'), ('mga', 'MGA (Malta)'), ('ukgc', 'UKGC (UK)'), ('curacao', 'Curaçao eGaming'), ('other', 'Altra licenza'), ('none', 'Nessuna licenza')], default='adm', max_length=10)),
                ('license_number', models.CharField(blank=True, max_length=60)),
                ('official_url', models.URLField(help_text='URL ufficiale del bookmaker (non affiliato).')),
                ('affiliate_url', models.URLField(blank=True, help_text="Link affiliato. Se vuoto si usa l'official_url.")),
                ('rating', models.DecimalField(decimal_places=1, default=0, help_text='Voto editoriale 0–5 (es. 4.5).', max_digits=3)),
                ('short_description', models.CharField(blank=True, help_text='Una riga che descrive il bookmaker (mostrata in homepage).', max_length=240)),
                ('full_review', models.TextField(blank=True, help_text='Recensione completa (mostrata nella scheda dedicata).')),
                ('pros', models.TextField(blank=True, help_text='Elenco punti di forza, uno per riga.')),
                ('cons', models.TextField(blank=True, help_text='Elenco punti deboli, uno per riga.')),
                ('is_published', models.BooleanField(default=True, help_text='Se False, il bookmaker non appare sul sito pubblico.')),
                ('order', models.PositiveIntegerField(default=100, help_text='Ordinamento (più basso = più in alto).')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bookmaker',
                'verbose_name_plural': 'Bookmaker',
                'ordering': ['order', '-rating', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus_type', models.CharField(choices=[('welcome_sport', 'Benvenuto scommesse'), ('welcome_casino', 'Benvenuto casinò'), ('freebet', 'Free bet'), ('freespin', 'Free spin'), ('cashback', 'Cashback / rimborso'), ('no_deposit', 'Senza deposito'), ('reload', 'Ricarica'), ('other', 'Altro')], default='welcome_sport', max_length=20)),
                ('title', models.CharField(help_text='Es. "Bonus benvenuto fino a 100€" o "200% fino a 1000€ + 50 free spin".', max_length=160)),
                ('amount_text', models.CharField(blank=True, help_text='Importo sintetico, es. "100€", "1000€ + 50 FS".', max_length=80)),
                ('description', models.TextField(blank=True)),
                ('terms_summary', models.TextField(blank=True, help_text='Sintesi dei termini chiave (deposito minimo, requisiti di scommessa, scadenza).')),
                ('terms_url', models.URLField(blank=True, help_text='Link ai T&C completi sul sito del bookmaker.')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Mostra in evidenza nelle griglie del comparatore.')),
                ('order', models.PositiveIntegerField(default=100)),
                ('manual_override', models.BooleanField(default=False, help_text='Se True, lo scraper automatico non sovrascrive questo bonus.')),
                ('scrape_source_url', models.URLField(blank=True, help_text='URL della pagina promozioni del bookmaker usata dallo scraper.')),
                ('last_scraped_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bookmaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to='bonus_comparatore.bookmaker')),
            ],
            options={
                'verbose_name': 'Bonus',
                'verbose_name_plural': 'Bonus',
                'ordering': ['order', '-updated_at'],
            },
        ),
    ]
