# Generated by Django 6.0.4 on 2026-06-23 11:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonus_comparatore', '0002_seed_bookmakers'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('referer', models.URLField(blank=True, max_length=500)),
                ('to_affiliate', models.BooleanField(default=False, help_text='True se il click è andato a un link affiliato (non al sito ufficiale).')),
                ('bookmaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='bonus_comparatore.bookmaker')),
            ],
            options={
                'verbose_name': 'Click',
                'verbose_name_plural': 'Click log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['bookmaker', 'created_at'], name='bonus_compa_bookmak_00bd46_idx')],
            },
        ),
    ]
