# Generated by Django 6.0.4 on 2026-06-26 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonus_comparatore', '0005_add_brand_colors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmaker',
            name='brand_color',
            field=models.CharField(blank=True, default='#111827', help_text='Colore di sfondo del banner (es. #ffffff per bianco, #1b5e20 per verde Sisal).', max_length=20),
        ),
        migrations.AlterField(
            model_name='bookmaker',
            name='brand_text_dark',
            field=models.BooleanField(default=False, help_text='Testo scuro (nero) sul banner. Spuntare per sfondi chiari (es. Lottomatica bianco).'),
        ),
        migrations.AlterField(
            model_name='bookmaker',
            name='cta_color',
            field=models.CharField(blank=True, default='#ffd600', help_text='Colore del bottone CTA nel banner (es. #1565c0 per blu).', max_length=20),
        ),
        migrations.AlterField(
            model_name='bookmaker',
            name='cta_text_color',
            field=models.CharField(blank=True, default='#111111', help_text='Colore del testo nel bottone CTA (es. #ffffff per bianco).', max_length=20),
        ),
    ]
