# Generated by Django 5.1.15 on 2026-04-29 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_key', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=80)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['table_key', 'name'],
                'indexes': [models.Index(fields=['user', 'table_key'], name='core_savedv_user_id_1f170f_idx'), models.Index(fields=['user', 'table_key', 'is_default'], name='core_savedv_user_id_3ccb6f_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'table_key', 'name'), name='uniq_savedview_per_table_per_user')],
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128)),
                ('value', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'key'], name='core_userpr_user_id_7fb877_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'key'), name='uniq_userpreference_per_user_per_key')],
            },
        ),
    ]
