# Generated by Django 6.0.4 on 2026-06-14 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_landingvisit_landingclick'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='event_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp riportato dalla fonte, se presente nel postback.', null=True),
        ),
        migrations.AlterField(
            model_name='leadsource',
            name='kind',
            field=models.CharField(choices=[('trackbox', 'TrackBox'), ('irev', 'IREV'), ('affinitrax', 'Affinitrax'), ('v3', 'Integration v3 (api_token)'), ('mediafront', 'Mediafront (Midas)'), ('spmmonster', 'SPM Monster')], max_length=20),
        ),
    ]
