# Generated by Django 6.0.4 on 2026-06-15 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_alter_lead_event_at_alter_leadsource_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadsource',
            name='logo_url',
            field=models.URLField(blank=True, help_text="Link a un'immagine (logo del broker). Mostrato accanto al nome.", verbose_name='Foto / Logo (URL)'),
        ),
    ]
