# Generated by Django 6.0.4 on 2026-06-15 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0011_leadsource_logo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='country',
            field=models.CharField(blank=True, db_index=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(db_index=True, default='postback', max_length=64),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
    ]
