# Generated by Django 6.0.4 on 2026-06-15 23:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0012_alter_lead_country_alter_lead_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Codice corto auto-generato (es. jJzR86).', max_length=12, unique=True)),
                ('name', models.CharField(blank=True, help_text="Etichetta interna (es. 'FB - IREV crypto').", max_length=120)),
                ('destination', models.URLField(help_text='Dove reindirizzare il click (landing del broker o offerta).')),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('source', models.ForeignKey(blank=True, help_text='Broker associato (opzionale).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracking_links', to='leads.leadsource')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
