# Generated by Django 6.0.4 on 2026-06-17 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0013_trackinglink'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadsource',
            name='landing_custom_html',
            field=models.TextField(blank=True, help_text='Se valorizzato, /b/<slug>/ serve questo HTML grezzo (landing clonata) invece del template. Il form deve postare a /b/<slug>/submit/.', verbose_name='HTML landing personalizzato'),
        ),
    ]
