# Generated by Django 6.0.4 on 2026-06-24 15:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0018_leadsource_hypernet'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreLanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Etichetta interna (es. 'Pre-lander FB crypto').", max_length=120)),
                ('url', models.URLField(help_text='URL della pre-landing esterna (dove è ospitata).')),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('tracking_link', models.ForeignKey(blank=True, help_text='Link di tracciamento da mettere nel bottone della pre-landing.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prelandings', to='leads.trackinglink')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
