from django.urls import path

from .views import (
    BrokerListView,
    GuideView,
    IrevBrokerCreateView,
    IrevBrokerDeleteView,
    IrevBrokerUpdateView,
    LeadErrorListView,
    LeadListView,
    LeadRerouteView,
    LeadPushView,
    LeadSyncSelectedView,
    LeadTogglePaidView,
    OpenAffBrokerCreateView,
    OpenAffBrokerDeleteView,
    OpenAffBrokerSyncView,
    OpenAffBrokerUpdateView,
    GlobalTradeBrokerCreateView,
    GlobalTradeBrokerDeleteView,
    GlobalTradeBrokerSyncView,
    GlobalTradeBrokerUpdateView,
    OneCryptBrokerCreateView,
    OneCryptBrokerDeleteView,
    OneCryptBrokerSyncView,
    OneCryptBrokerUpdateView,
    CpaForgeBrokerCreateView,
    CpaForgeBrokerDeleteView,
    CpaForgeBrokerSyncView,
    CpaForgeBrokerUpdateView,
    SpmMonsterBrokerCreateView,
    SpmMonsterBrokerDeleteView,
    SpmMonsterBrokerSyncView,
    SpmMonsterBrokerUpdateView,
    SyncAllView,
    GalassiaBrokerCreateView,
    GalassiaBrokerDeleteView,
    GalassiaBrokerSyncView,
    GalassiaBrokerUpdateView,
    TYourAdsBrokerCreateView,
    TYourAdsBrokerDeleteView,
    TYourAdsBrokerUpdateView,
    TrackboxBrokerCreateView,
    TrackboxBrokerDeleteView,
    TrackboxBrokerSyncView,
    TrackboxBrokerUpdateView,
    TrackingCodeView,
)

app_name = "tracking"

urlpatterns = [
    path("", LeadListView.as_view(), name="lead_list"),
    path("errori/", LeadErrorListView.as_view(), name="lead_errors"),
    path("leads/<int:pk>/push/", LeadPushView.as_view(), name="lead_push"),
    path("leads/<int:pk>/paid/", LeadTogglePaidView.as_view(), name="lead_toggle_paid"),
    path("leads/sync-selected/", LeadSyncSelectedView.as_view(), name="lead_sync_selected"),
    path("leads/<int:pk>/reroute/", LeadRerouteView.as_view(), name="lead_reroute"),
    path("sync-all/", SyncAllView.as_view(), name="sync_all"),
    path("guida/", GuideView.as_view(), name="guide"),
    # Broker API — lista unificata
    path("brokers/", BrokerListView.as_view(), name="broker_list"),
    # TrackBox
    path("brokers/trackbox/new/", TrackboxBrokerCreateView.as_view(), name="broker_create"),
    path("brokers/trackbox/<int:pk>/edit/", TrackboxBrokerUpdateView.as_view(), name="broker_edit"),
    path("brokers/trackbox/<int:pk>/delete/", TrackboxBrokerDeleteView.as_view(), name="broker_delete"),
    path("brokers/trackbox/<int:pk>/sync/", TrackboxBrokerSyncView.as_view(), name="broker_sync"),
    # IREV
    path("brokers/irev/new/", IrevBrokerCreateView.as_view(), name="irev_create"),
    path("brokers/irev/<int:pk>/edit/", IrevBrokerUpdateView.as_view(), name="irev_edit"),
    path("brokers/irev/<int:pk>/delete/", IrevBrokerDeleteView.as_view(), name="irev_delete"),
    # SPM Monster
    path("brokers/spm/new/", SpmMonsterBrokerCreateView.as_view(), name="spm_create"),
    path("brokers/spm/<int:pk>/edit/", SpmMonsterBrokerUpdateView.as_view(), name="spm_edit"),
    path("brokers/spm/<int:pk>/delete/", SpmMonsterBrokerDeleteView.as_view(), name="spm_delete"),
    path("brokers/spm/<int:pk>/sync/", SpmMonsterBrokerSyncView.as_view(), name="spm_sync"),

    path("brokers/tyourads/new/", TYourAdsBrokerCreateView.as_view(), name="tyourads_create"),
    path("brokers/tyourads/<int:pk>/edit/", TYourAdsBrokerUpdateView.as_view(), name="tyourads_edit"),
    path("brokers/tyourads/<int:pk>/delete/", TYourAdsBrokerDeleteView.as_view(), name="tyourads_delete"),

    path("brokers/galassia/new/", GalassiaBrokerCreateView.as_view(), name="galassia_create"),
    path("brokers/galassia/<int:pk>/edit/", GalassiaBrokerUpdateView.as_view(), name="galassia_edit"),
    path("brokers/galassia/<int:pk>/delete/", GalassiaBrokerDeleteView.as_view(), name="galassia_delete"),
    path("brokers/galassia/<int:pk>/sync/", GalassiaBrokerSyncView.as_view(), name="galassia_sync"),
    # OpenAFF
    path("brokers/openaff/new/", OpenAffBrokerCreateView.as_view(), name="openaff_create"),
    path("brokers/openaff/<int:pk>/edit/", OpenAffBrokerUpdateView.as_view(), name="openaff_edit"),
    path("brokers/openaff/<int:pk>/delete/", OpenAffBrokerDeleteView.as_view(), name="openaff_delete"),
    path("brokers/openaff/<int:pk>/sync/", OpenAffBrokerSyncView.as_view(), name="openaff_sync"),
    # GlobalTrade
    path("brokers/globaltrade/new/", GlobalTradeBrokerCreateView.as_view(), name="globaltrade_create"),
    path("brokers/globaltrade/<int:pk>/edit/", GlobalTradeBrokerUpdateView.as_view(), name="globaltrade_edit"),
    path("brokers/globaltrade/<int:pk>/delete/", GlobalTradeBrokerDeleteView.as_view(), name="globaltrade_delete"),
    path("brokers/globaltrade/<int:pk>/sync/", GlobalTradeBrokerSyncView.as_view(), name="globaltrade_sync"),
    # OneCrypt
    path("brokers/onecrypt/new/", OneCryptBrokerCreateView.as_view(), name="onecrypt_create"),
    path("brokers/onecrypt/<int:pk>/edit/", OneCryptBrokerUpdateView.as_view(), name="onecrypt_edit"),
    path("brokers/onecrypt/<int:pk>/delete/", OneCryptBrokerDeleteView.as_view(), name="onecrypt_delete"),
    path("brokers/onecrypt/<int:pk>/sync/", OneCryptBrokerSyncView.as_view(), name="onecrypt_sync"),
    path("brokers/cpaforge/new/", CpaForgeBrokerCreateView.as_view(), name="cpaforge_create"),
    path("brokers/cpaforge/<int:pk>/edit/", CpaForgeBrokerUpdateView.as_view(), name="cpaforge_edit"),
    path("brokers/cpaforge/<int:pk>/delete/", CpaForgeBrokerDeleteView.as_view(), name="cpaforge_delete"),
    path("brokers/cpaforge/<int:pk>/sync/", CpaForgeBrokerSyncView.as_view(), name="cpaforge_sync"),
    # Codice tracciamento per landing esterna (snippet form)
    path("brokers/<str:kind>/<int:pk>/code/", TrackingCodeView.as_view(), name="broker_code"),
]
