# Generated by Django 6.0.4 on 2026-06-26 19:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrackboxBroker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Etichetta interna, es. 'FINTECHGURUS'.", max_length=120, verbose_name='Nome')),
                ('base_url', models.URLField(help_text='Es. https://track.fintechgurus.org', verbose_name='Base URL')),
                ('username', models.CharField(help_text='Header x-trackbox-username.', max_length=120, verbose_name='Username')),
                ('password', models.CharField(help_text='Header x-trackbox-password.', max_length=255, verbose_name='Password')),
                ('push_key', models.CharField(help_text='Chiave x-api-key per il PUSH (/api/signup/procform).', max_length=255, verbose_name='x-api-key PUSH')),
                ('pull_key', models.CharField(help_text='Chiave x-api-key per il PULL (/api/pull/customers) — DIVERSA dalla push.', max_length=255, verbose_name='x-api-key PULL')),
                ('ai', models.CharField(max_length=64, verbose_name='ai (affiliate id)')),
                ('ci', models.CharField(default='1', max_length=64, verbose_name='ci')),
                ('gi', models.CharField(max_length=64, verbose_name='gi (group id)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attivo')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Broker TrackBox',
                'verbose_name_plural': 'Broker TrackBox',
                'ordering': ['name'],
            },
        ),
    ]
