# Generated by Django 6.0.4 on 2026-06-26 19:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_id', models.CharField(db_index=True, help_text='Id univoco nostro, chiave di aggancio del postback.', max_length=64, unique=True, verbose_name='Click id (affclickid)')),
                ('broker_lead_id', models.CharField(blank=True, db_index=True, help_text='Id ritornato dal broker al push (customerId/uniqueid).', max_length=128, verbose_name='Id lead broker')),
                ('firstname', models.CharField(blank=True, max_length=120, verbose_name='Nome')),
                ('lastname', models.CharField(blank=True, max_length=120, verbose_name='Cognome')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Telefono')),
                ('country', models.CharField(blank=True, max_length=8, verbose_name='Paese')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('status', models.CharField(blank=True, max_length=120, verbose_name='Stato')),
                ('is_deposit', models.BooleanField(default=False, verbose_name='FTD')),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('event_at', models.DateTimeField(blank=True, null=True, verbose_name='Data evento')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('broker', models.ForeignKey(blank=True, help_text='Broker di destinazione del lead.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='tracking.trackboxbroker')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Lead',
                'ordering': ['-created_at'],
            },
        ),
    ]
