# Generated by Django 6.0.4 on 2026-06-26 19:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_lead'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.BooleanField(default=False)),
                ('response', models.JSONField(blank=True, default=dict)),
                ('error', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('broker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='push_logs', to='tracking.trackboxbroker')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_logs', to='tracking.lead')),
            ],
            options={
                'verbose_name': 'Push log',
                'verbose_name_plural': 'Push log',
                'ordering': ['-created_at'],
            },
        ),
    ]
