# Generated by Django 6.0.4 on 2026-06-26 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_pushlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackboxbroker',
            name='landing_slug',
            field=models.SlugField(blank=True, help_text='Slug della landing pubblica: /lp/<slug>/. Lascia vuoto se il broker non usa una landing dedicata.', max_length=60, null=True, unique=True, verbose_name='Slug landing'),
        ),
    ]
