# Generated by Django 6.0.4 on 2026-06-26 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_trackboxbroker_landing_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackboxbroker',
            name='funnel',
            field=models.CharField(blank=True, help_text="Nome funnel inviato al broker nel campo 'so' (visibile nei report TrackBox). Se vuoto usa il nome del broker.", max_length=120, verbose_name='Funnel'),
        ),
    ]
