# Generated by Django 6.0.4 on 2026-06-26 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_trackboxbroker_funnel'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackboxbroker',
            name='note',
            field=models.CharField(blank=True, help_text='Nota interna / nome alternativo del broker.', max_length=255, verbose_name='Note'),
        ),
    ]
