# Generated by Django 6.0.4 — broker generico (TrackBox/IREV) con copia dati.

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def copy_broker_refs(apps, schema_editor):
    """Copia il vecchio FK broker (→ TrackboxBroker) nei nuovi campi generici,
    e il nome broker in PushLog.broker_label. Niente dato perso."""
    Lead = apps.get_model("tracking", "Lead")
    PushLog = apps.get_model("tracking", "PushLog")
    TrackboxBroker = apps.get_model("tracking", "TrackboxBroker")
    ContentType = apps.get_model("contenttypes", "ContentType")

    ct = ContentType.objects.filter(
        app_label="tracking", model="trackboxbroker").first()
    if ct:
        for lead in Lead.objects.exclude(broker_id=None):
            Lead.objects.filter(pk=lead.pk).update(
                broker_content_type_id=ct.id,
                broker_object_id=lead.broker_id)

    names = {b.id: b.name for b in TrackboxBroker.objects.all()}
    for pl in PushLog.objects.exclude(broker_id=None):
        PushLog.objects.filter(pk=pl.pk).update(
            broker_label=names.get(pl.broker_id, ""))


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tracking', '0006_trackboxbroker_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='IrevBroker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nome')),
                ('base_url', models.URLField(help_text='Es. https://stylishwnt.com', verbose_name='Base URL')),
                ('token', models.CharField(help_text='Header Authorization.', max_length=255, verbose_name='API token')),
                ('affiliate_id', models.CharField(max_length=64, verbose_name='affiliate_id')),
                ('offer_id', models.CharField(max_length=64, verbose_name='offer_id')),
                ('goal_lead_uuid', models.CharField(blank=True, max_length=64, verbose_name='Goal UUID Lead')),
                ('goal_ftd_uuid', models.CharField(blank=True, help_text='UUID del goal FTD: serve a riconoscere i depositi.', max_length=64, verbose_name='Goal UUID FTD')),
                ('landing_slug', models.SlugField(blank=True, help_text='Landing pubblica: /lp/<slug>/.', max_length=60, null=True, unique=True, verbose_name='Slug landing')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Note')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attivo')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Broker IREV',
                'verbose_name_plural': 'Broker IREV',
                'ordering': ['name'],
            },
        ),
        # 1) Aggiungi i nuovi campi (generici + label) PRIMA di rimuovere i vecchi.
        migrations.AddField(
            model_name='lead',
            name='broker_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='lead',
            name='broker_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pushlog',
            name='broker_label',
            field=models.CharField(blank=True, max_length=120),
        ),
        # 2) Copia i dati dai vecchi FK.
        migrations.RunPython(copy_broker_refs, noop),
        # 3) Rimuovi i vecchi FK.
        migrations.RemoveField(model_name='lead', name='broker'),
        migrations.RemoveField(model_name='pushlog', name='broker'),
        # 4) Alter vari.
        migrations.AlterField(
            model_name='lead',
            name='broker_lead_id',
            field=models.CharField(blank=True, db_index=True, max_length=128, verbose_name='Id lead broker'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='click_id',
            field=models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Click id (affclickid)'),
        ),
        migrations.AlterField(
            model_name='trackboxbroker',
            name='funnel',
            field=models.CharField(blank=True, help_text="Nome funnel inviato nel campo 'so'. Se vuoto usa il nome.", max_length=120, verbose_name='Funnel'),
        ),
        migrations.AlterField(
            model_name='trackboxbroker',
            name='landing_slug',
            field=models.SlugField(blank=True, help_text='Landing pubblica: /lp/<slug>/.', max_length=60, null=True, unique=True, verbose_name='Slug landing'),
        ),
    ]
