# Generated by Django 6.0.4 on 2026-06-26 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0007_irevbroker_remove_lead_broker_remove_pushlog_broker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='irevbroker',
            name='funnel',
            field=models.CharField(blank=True, help_text="Solo etichetta nostra: IREV NON riceve il funnel nel push (lo decide dall'offer_id). Serve per riferimento/report.", max_length=120, verbose_name='Funnel'),
        ),
    ]
