# Generated by Django 6.0.4 on 2026-06-26 22:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0008_irevbroker_funnel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpmMonsterBroker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nome')),
                ('base_url', models.URLField(help_text='Es. https://spmteamone.it.com', verbose_name='Base URL')),
                ('api_key', models.CharField(max_length=255, verbose_name='x-api-key')),
                ('affc', models.CharField(max_length=64, verbose_name='affc (affiliate code)')),
                ('bxc', models.CharField(max_length=64, verbose_name='bxc (box code)')),
                ('vtc', models.CharField(max_length=64, verbose_name='vtc (vertical code)')),
                ('funnel', models.CharField(blank=True, help_text='Nome funnel inviato nel push. Se vuoto usa il nome.', max_length=120, verbose_name='Funnel')),
                ('landing_slug', models.SlugField(blank=True, help_text='Landing pubblica: /lp/<slug>/.', max_length=60, null=True, unique=True, verbose_name='Slug landing')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Note')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attivo')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Broker SPM Monster',
                'verbose_name_plural': 'Broker SPM Monster',
                'ordering': ['name'],
            },
        ),
    ]
