# Generated by Django 6.0.4 on 2026-06-26 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0009_spmmonsterbroker'),
    ]

    operations = [
        migrations.AddField(
            model_name='irevbroker',
            name='landing_html',
            field=models.TextField(blank=True, help_text="HTML completo della landing di QUESTO broker. Se valorizzato, /lp/<slug>/ mostra questo invece del form standard. Deve contenere un <form method='POST' action='/lp/<slug>/'> con i campi: firstname, lastname, email, phone, country.", verbose_name='HTML landing personalizzata'),
        ),
        migrations.AddField(
            model_name='spmmonsterbroker',
            name='landing_html',
            field=models.TextField(blank=True, help_text="HTML completo della landing di QUESTO broker. Se valorizzato, /lp/<slug>/ mostra questo invece del form standard. Deve contenere un <form method='POST' action='/lp/<slug>/'> con i campi: firstname, lastname, email, phone, country.", verbose_name='HTML landing personalizzata'),
        ),
        migrations.AddField(
            model_name='trackboxbroker',
            name='landing_html',
            field=models.TextField(blank=True, help_text="HTML completo della landing di QUESTO broker. Se valorizzato, /lp/<slug>/ mostra questo invece del form standard. Deve contenere un <form method='POST' action='/lp/<slug>/'> con i campi: firstname, lastname, email, phone, country.", verbose_name='HTML landing personalizzata'),
        ),
    ]
