# Generated by Django 6.0.4 on 2026-06-26 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0010_irevbroker_landing_html_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='irevbroker',
            name='landing_brand',
            field=models.CharField(blank=True, help_text='Nome/logo mostrato sulla landing pubblica (visitor-facing). Il nome interno del broker resta invariato nel CRM.', max_length=120, verbose_name='Brand landing'),
        ),
        migrations.AddField(
            model_name='spmmonsterbroker',
            name='landing_brand',
            field=models.CharField(blank=True, help_text='Nome/logo mostrato sulla landing pubblica (visitor-facing). Il nome interno del broker resta invariato nel CRM.', max_length=120, verbose_name='Brand landing'),
        ),
        migrations.AddField(
            model_name='trackboxbroker',
            name='landing_brand',
            field=models.CharField(blank=True, help_text='Nome/logo mostrato sulla landing pubblica (visitor-facing). Il nome interno del broker resta invariato nel CRM.', max_length=120, verbose_name='Brand landing'),
        ),
    ]
