# Generated by Django 6.0.4 on 2026-06-27 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0011_irevbroker_landing_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='note',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nota'),
        ),
    ]
