# Generated by Django 6.0.4 on 2026-06-27 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0012_lead_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='reject_reason',
            field=models.CharField(blank=True, max_length=255, verbose_name='Motivo rifiuto'),
        ),
        migrations.AddField(
            model_name='lead',
            name='stage',
            field=models.CharField(choices=[('nuovo', 'Nuovo'), ('inviato', 'Inviato'), ('registrato', 'Registrato'), ('kyc', 'Verificato (KYC)'), ('ftd', 'FTD'), ('retained', 'Retained'), ('rifiutato', 'Rifiutato')], db_index=True, default='nuovo', max_length=20, verbose_name='Fase'),
        ),
    ]
