# Generated by Django 6.0.4 on 2026-06-27 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0013_lead_reject_reason_lead_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackboxbroker',
            name='extra_params',
            field=models.JSONField(blank=True, default=dict, help_text='Parametri aggiuntivi inviati nel push, specifici del broker. Es. {"MPC_7": "LIVE", "MPC_8": "59704"}. Vuoto = nessuno.', verbose_name='Parametri extra (JSON)'),
        ),
    ]
