# Generated by Django 6.0.4 on 2026-06-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0014_trackboxbroker_extra_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='last_pull_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ultimo agg. API'),
        ),
    ]
