# Generated by Django 6.0.4 on 2026-06-29 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0015_lead_last_pull_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='stage',
            field=models.CharField(choices=[('nuovo', 'Nuovo'), ('no_answer', 'Nessuna risposta'), ('not_interested', 'Nessun interesse'), ('callback', 'Call back'), ('ftd', 'FTD')], db_index=True, default='nuovo', max_length=20, verbose_name='Fase'),
        ),
    ]
