# Generated by Django 6.0.4 on 2026-06-29 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0017_remap_lead_stages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='stage',
            field=models.CharField(choices=[('nuovo', 'Nuovo'), ('instant_call', 'Instant call'), ('in_work', 'In work'), ('no_answer', 'Nessuna risposta'), ('callback', 'Call back'), ('basso_potenziale', 'Basso potenziale'), ('nessun_potenziale', 'Nessun potenziale'), ('not_interested', 'Nessun interesse'), ('ftd', 'FTD')], db_index=True, default='nuovo', max_length=20, verbose_name='Fase'),
        ),
    ]
