# Generated by Django 6.0.4 on 2026-06-29 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0018_alter_lead_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackboxbroker',
            name='match_by_contact',
            field=models.BooleanField(default=False, help_text='Se attivo, la pull aggancia i lead anche per email/telefono (oltre a click_id/id). Da usare solo per broker che NON restituiscono il nostro click_id nella pull (es. Link 10).', verbose_name='Aggancio per email/telefono'),
        ),
    ]
