# Generated by Django 6.0.4 on 2026-06-29 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0019_trackboxbroker_match_by_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='spmmonsterbroker',
            name='match_by_contact',
            field=models.BooleanField(default=False, help_text='Se attivo, la pull aggancia i lead anche per email/telefono (oltre a click_id/id). Attivalo solo se per questo broker non riusciamo a leggere gli status nel modo normale.', verbose_name='Aggancio per email/telefono'),
        ),
    ]
