# Generated by Django 6.0.4 on 2026-06-29 20:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0020_spmmonsterbroker_match_by_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='TYourAdsBroker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nome')),
                ('base_url', models.URLField(default='https://tyourads-api.com', help_text='Es. https://tyourads-api.com', verbose_name='Base URL')),
                ('api_key', models.CharField(max_length=255, verbose_name='Api-Key')),
                ('offer_name', models.CharField(blank=True, help_text='Es. "Bitcoin Bank". Se vuoto usa il nome del broker.', max_length=160, verbose_name='offerName')),
                ('offer_website', models.CharField(blank=True, max_length=200, verbose_name='offerWebsite')),
                ('landing_slug', models.SlugField(blank=True, help_text='Landing pubblica: /lp/<slug>/.', max_length=60, null=True, unique=True, verbose_name='Slug landing')),
                ('landing_brand', models.CharField(blank=True, help_text='Nome/logo mostrato sulla landing pubblica (visitor-facing).', max_length=120, verbose_name='Brand landing')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Note')),
                ('landing_html', models.TextField(blank=True, help_text="HTML completo della landing. Deve contenere un <form method='POST' action='/lp/<slug>/'> con i campi: firstname, lastname, email, phone, country.", verbose_name='HTML landing personalizzata')),
                ('match_by_contact', models.BooleanField(default=False, help_text='Aggancia i lead anche per email/telefono nella pull/postback.', verbose_name='Aggancio per email/telefono')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attivo')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Broker TYourAds',
                'verbose_name_plural': 'Broker TYourAds',
                'ordering': ['name'],
            },
        ),
    ]
