# Generated by Django 6.0.4 on 2026-06-29 21:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0021_tyouradsbroker'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalassiaBroker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nome')),
                ('base_url', models.URLField(help_text='Es. https://elnopy.crypto-galassia.com', verbose_name='Base URL')),
                ('api_token', models.CharField(max_length=255, verbose_name='api_token')),
                ('link_id', models.CharField(max_length=40, verbose_name='link_id')),
                ('funnel', models.CharField(blank=True, help_text="Inviato come 'funnel'. Se vuoto usa il nome del broker.", max_length=120, verbose_name='Funnel')),
                ('source', models.CharField(blank=True, help_text="Inviato come 'source' (es. facebook).", max_length=120, verbose_name='Source')),
                ('country', models.CharField(blank=True, default='IT', help_text='ISO 3166-1 alpha-2. Se il lead non ha country, usa questo.', max_length=8, verbose_name='Country default')),
                ('language', models.CharField(blank=True, default='it', help_text="ISO 639-1 inviato come 'language'.", max_length=8, verbose_name='Language')),
                ('landing_slug', models.SlugField(blank=True, help_text='Landing pubblica: /lp/<slug>/.', max_length=60, null=True, unique=True, verbose_name='Slug landing')),
                ('landing_brand', models.CharField(blank=True, help_text='Nome/logo mostrato sulla landing (visitor-facing).', max_length=120, verbose_name='Brand landing')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Note')),
                ('landing_html', models.TextField(blank=True, help_text='HTML completo della landing. Form POST a /lp/<slug>/ con campi: firstname, lastname, email, phone, country.', verbose_name='HTML landing personalizzata')),
                ('match_by_contact', models.BooleanField(default=False, help_text='Aggancio extra per email/telefono nella pull, se serve.', verbose_name='Aggancio per email/telefono')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attivo')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Broker Galassia',
                'verbose_name_plural': 'Broker Galassia',
                'ordering': ['name'],
            },
        ),
    ]
