# Generated by Django 6.0.4 on 2026-06-30 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0022_galassiabroker'),
    ]

    operations = [
        migrations.AddField(
            model_name='irevbroker',
            name='api_path',
            field=models.CharField(blank=True, help_text='Path push/pull se diverso dal default. Vuoto = /affiliates/v2/leads. Es. /api/affiliates/v2/leads', max_length=120, verbose_name='API path (override)'),
        ),
        migrations.AddField(
            model_name='irevbroker',
            name='extra_params',
            field=models.JSONField(blank=True, default=dict, help_text='Campi extra nel push, es. {"aff_sub3": "Eterna Immediata"}. Vuoto = nessuno.', verbose_name='Parametri extra (JSON)'),
        ),
    ]
