# Generated by Django 6.0.4 on 2026-06-30 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0023_irevbroker_api_path_irevbroker_extra_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='irevbroker',
            name='use_pull',
            field=models.BooleanField(default=False, help_text='Se attivo, gli stati/FTD arrivano via pull get-leads (goal FTD). Se OFF (default) lo stato arriva via postback. Tenere OFF sui broker esistenti.', verbose_name='Aggiorna stati via PULL'),
        ),
    ]
