# Generated by Django 6.0.4 on 2026-06-30 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0024_irevbroker_use_pull'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TYourAdsBroker',
        ),
    ]
