# Generated by Django 6.0.4 on 2026-07-01 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0026_tyouradsbroker'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='duplicate_reason',
            field=models.CharField(blank=True, max_length=40, verbose_name='Motivo duplicato'),
        ),
        migrations.AddField(
            model_name='lead',
            name='is_duplicate',
            field=models.BooleanField(default=False, verbose_name='Duplicato'),
        ),
    ]
