# Generated by Django 6.0.4 on 2026-07-10 08:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0027_lead_duplicate_reason_lead_is_duplicate'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenAffBroker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nome')),
                ('base_url', models.URLField(help_text='URL di invio lead dato dal manager. Es. http://vip.kofoboo.com', verbose_name='API domain')),
                ('token', models.CharField(help_text='Token dal pannello (tracker.openaff.com/profile#tokens) per leggere gli stati.', max_length=1024, verbose_name='Token PULL (Bearer)')),
                ('aff_id', models.CharField(help_text='Affiliate ID OpenAFF.', max_length=64, verbose_name='aff_id')),
                ('offer_id', models.CharField(default='1737', help_text='SEMPRE 1737 (cambiarlo dà errore).', max_length=32, verbose_name='offer_id')),
                ('funnel', models.CharField(blank=True, help_text='Inviato come aff_sub3. Se vuoto usa il nome del broker.', max_length=120, verbose_name='Funnel')),
                ('landing_slug', models.SlugField(blank=True, help_text='Landing pubblica: /lp/<slug>/.', max_length=60, null=True, unique=True, verbose_name='Slug landing')),
                ('landing_brand', models.CharField(blank=True, help_text='Nome/logo mostrato sulla landing (visitor-facing).', max_length=120, verbose_name='Brand landing')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Note')),
                ('landing_html', models.TextField(blank=True, help_text='HTML completo della landing. Form POST a /lp/<slug>/ con campi: firstname, lastname, email, phone, country.', verbose_name='HTML landing personalizzata')),
                ('match_by_contact', models.BooleanField(default=False, help_text='Aggancio extra per email/telefono nella pull, se serve.', verbose_name='Aggancio per email/telefono')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attivo')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Broker OpenAFF',
                'verbose_name_plural': 'Broker OpenAFF',
                'ordering': ['name'],
            },
        ),
    ]
