# Generated by Django 6.0.4 on 2026-07-10 11:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0028_openaffbroker'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalTradeBroker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nome')),
                ('base_url', models.URLField(default='https://crm.globaltrade-company.live', help_text='Dominio CRM. Push=/api/leads, pull=/api/web-master/leads.', verbose_name='Base URL')),
                ('token', models.CharField(blank=True, help_text='Token JWT del pannello per leggere gli stati (pull).', max_length=1024, verbose_name='Token PULL (Bearer)')),
                ('user_id', models.CharField(help_text='ID web-master GlobalTrade (es. 276).', max_length=64, verbose_name='user_id')),
                ('source', models.CharField(blank=True, help_text='Sorgente inviata al broker (es. Adverterra).', max_length=120, verbose_name='source')),
                ('funnel', models.CharField(blank=True, help_text='Inviato come landing_name. Se vuoto usa il nome del broker.', max_length=120, verbose_name='Funnel')),
                ('landing_domain', models.CharField(default='goicetimes.com', help_text="Inviato come 'landing' (dominio dove gira la landing).", max_length=120, verbose_name='Dominio landing')),
                ('landing_slug', models.SlugField(blank=True, help_text='Landing pubblica: /lp/<slug>/.', max_length=60, null=True, unique=True, verbose_name='Slug landing')),
                ('landing_brand', models.CharField(blank=True, help_text='Nome/logo mostrato sulla landing (visitor-facing).', max_length=120, verbose_name='Brand landing')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Note')),
                ('landing_html', models.TextField(blank=True, help_text='HTML completo della landing. Form POST a /lp/<slug>/ con campi: firstname, lastname, email, phone, country.', verbose_name='HTML landing personalizzata')),
                ('match_by_contact', models.BooleanField(default=False, help_text='Aggancio extra per email/telefono nella pull, se serve.', verbose_name='Aggancio per email/telefono')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attivo')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Broker GlobalTrade',
                'verbose_name_plural': 'Broker GlobalTrade',
                'ordering': ['name'],
            },
        ),
    ]
