# Generated by Django 6.0.4 on 2026-07-14 21:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0029_globaltradebroker'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneCryptBroker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nome')),
                ('base_url', models.URLField(default='http://api.onecrypt.link', help_text='Dominio API. Push=/api/lead/send, pull=/api/lead/feed.', verbose_name='Base URL API')),
                ('key', models.CharField(help_text='Chiave di accesso API (profilo onecrypt.link/u/profile).', max_length=255, verbose_name='API key')),
                ('web_id', models.CharField(blank=True, help_text='ID affiliato/webmaster (es. 100790).', max_length=64, verbose_name='Webmaster ID (web_id)')),
                ('offer_id', models.CharField(help_text='ID offerta nel sistema OneCrypt (per geo).', max_length=32, verbose_name='offer_id')),
                ('funnel', models.CharField(blank=True, help_text="Inviato nel campo 'comments'. Se vuoto usa il nome broker.", max_length=120, verbose_name='Funnel')),
                ('landing_slug', models.SlugField(blank=True, help_text='Landing pubblica: /lp/<slug>/.', max_length=60, null=True, unique=True, verbose_name='Slug landing')),
                ('landing_brand', models.CharField(blank=True, help_text='Nome/logo mostrato sulla landing (visitor-facing).', max_length=120, verbose_name='Brand landing')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Note')),
                ('landing_html', models.TextField(blank=True, help_text='HTML completo della landing. Form POST a /lp/<slug>/ con campi: firstname, lastname, email, phone, country.', verbose_name='HTML landing personalizzata')),
                ('match_by_contact', models.BooleanField(default=False, help_text='Aggancio extra per email/telefono nella pull, se serve.', verbose_name='Aggancio per email/telefono')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attivo')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Broker OneCrypt',
                'verbose_name_plural': 'Broker OneCrypt',
                'ordering': ['name'],
            },
        ),
    ]
