# Generated by Django 6.0.4 on 2026-07-16 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0031_cpaforgebroker'),
    ]

    operations = [
        migrations.AddField(
            model_name='irevbroker',
            name='dedup_since',
            field=models.DateTimeField(blank=True, help_text='Se valorizzato, il controllo duplicati considera solo i lead creati da questa data in poi. Utile al cambio broker/piattaforma: chi si era iscritto PRIMA non blocca le nuove registrazioni.', null=True, verbose_name='Antifrode da'),
        ),
    ]
