# Generated by Django 6.0.4 on 2026-07-18 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0032_irevbroker_dedup_since'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='ftd_paid',
            field=models.BooleanField(db_index=True, default=False, verbose_name='FTD pagata'),
        ),
    ]
