# Generated by Django 6.0.4 on 2026-07-23 09:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0034_affinitraxbroker'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadShakerBroker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nome')),
                ('base_url', models.URLField(default='https://crm.lead-shaker.live', help_text='Dominio API. Push=/api/leads, pull=/api/web-master/leads.', verbose_name='Base URL API')),
                ('token', models.CharField(help_text='Inviato come header Authorization: Bearer <token>.', max_length=2048, verbose_name='Token (Bearer)')),
                ('user_id', models.CharField(help_text="Il tuo ID assegnato da Lead-Shaker. Inviato come 'user_id'.", max_length=40, verbose_name='User ID (nel loro sistema)')),
                ('source', models.CharField(help_text="Inviato come 'source'. Es. 'Adverterra'.", max_length=120, verbose_name='Source (il tuo nickname da loro)')),
                ('funnel', models.CharField(blank=True, help_text="Inviato come 'landing_name'. Se vuoto usa il nome broker.", max_length=120, verbose_name='Funnel')),
                ('landing_slug', models.SlugField(blank=True, help_text='Landing pubblica: /lp/<slug>/.', max_length=60, null=True, unique=True, verbose_name='Slug landing')),
                ('landing_brand', models.CharField(blank=True, help_text='Nome/logo mostrato sulla landing (visitor-facing).', max_length=120, verbose_name='Brand landing')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Note')),
                ('landing_html', models.TextField(blank=True, help_text='HTML completo della landing. Form POST a /lp/<slug>/ con campi: firstname, lastname, email, phone, country.', verbose_name='HTML landing personalizzata')),
                ('match_by_contact', models.BooleanField(default=False, help_text='Aggancio extra per email/telefono nella pull, se serve.', verbose_name='Aggancio per email/telefono')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attivo')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Broker Lead-Shaker',
                'verbose_name_plural': 'Broker Lead-Shaker',
                'ordering': ['name'],
            },
        ),
    ]
