# Generated by Django 6.0.4 on 2026-07-24 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0035_leadshakerbroker'),
    ]

    operations = [
        migrations.AddField(
            model_name='openaffbroker',
            name='api_path',
            field=models.CharField(blank=True, help_text="Path dell'endpoint di invio lead. Vuoto = '/api' (default OpenAFF). Alcuni deployment (es. EPCERA) usano '/tracker'.", max_length=60, verbose_name='Path push'),
        ),
        migrations.AddField(
            model_name='openaffbroker',
            name='pull_url',
            field=models.URLField(default='https://tracker.openaff.com/api/get_client_conversions', help_text="Endpoint get_client_conversions per leggere gli stati. Puo' essere un dominio diverso da base_url (es. cabinet.epcera.com).", max_length=255, verbose_name='Pull cabinet URL'),
        ),
    ]
