# Generated by Django 6.0.4 on 2026-07-29 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0036_openaffbroker_api_path_openaffbroker_pull_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackboxbroker',
            name='push_base_url',
            field=models.URLField(blank=True, default='', help_text='Solo se il broker usa un dominio DIVERSO per il push (es. SoftTrack: push su https://apisofttrack.com, pull su https://tb.softtrack.net). Vuoto = usa il Base URL.', verbose_name='Base URL PUSH (se diverso)'),
        ),
    ]
