# Generated by Django 6.0.4 on 2026-08-04 15:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0037_trackboxbroker_push_base_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZenviorBroker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nome')),
                ('base_url', models.URLField(default='https://zenviorcrm.com', help_text='Dominio API. Push=/intake, pull=/api/affiliate/leads.', verbose_name='Base URL API')),
                ('api_key', models.CharField(help_text='Passata come ?api_key=... su ogni chiamata (push e pull).', max_length=255, verbose_name='API key')),
                ('funnel', models.CharField(blank=True, help_text="Inviato come 'offer'. Se vuoto usa il nome broker.", max_length=120, verbose_name='Funnel / offer')),
                ('landing_slug', models.SlugField(blank=True, help_text='Landing pubblica: /lp/<slug>/.', max_length=60, null=True, unique=True, verbose_name='Slug landing')),
                ('landing_brand', models.CharField(blank=True, help_text='Nome/logo mostrato sulla landing (visitor-facing).', max_length=120, verbose_name='Brand landing')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Note')),
                ('landing_html', models.TextField(blank=True, help_text='HTML completo della landing. Form POST a /lp/<slug>/ con campi: firstname, lastname, email, phone, country.', verbose_name='HTML landing personalizzata')),
                ('match_by_contact', models.BooleanField(default=False, help_text='Aggancio extra per email/telefono nella pull, se serve.', verbose_name='Aggancio per email/telefono')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attivo')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Broker Zenvior',
                'verbose_name_plural': 'Broker Zenvior',
                'ordering': ['name'],
            },
        ),
    ]
