# Generated by Django 5.1.15 on 2026-04-25 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('invoice_sent', 'Invoice sent'), ('invoice_paid', 'Invoice paid'), ('invoice_void', 'Invoice voided'), ('order_placed', 'Order placed'), ('new_mail', 'New mail')], max_length=32),
        ),
    ]
