# Generated by Django 5.1.15 on 2026-04-29 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('system', 'System'), ('billing', 'Billing'), ('mention', 'Mention'), ('comment', 'Comment'), ('security', 'Security')], max_length=16)),
                ('in_app', models.BooleanField(default=True)),
                ('email', models.BooleanField(default=False)),
                ('push', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(max_length=500, unique=True)),
                ('p256dh', models.CharField(max_length=200)),
                ('auth', models.CharField(max_length=64)),
                ('user_agent', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='notification',
            name='actor',
            field=models.ForeignKey(blank=True, help_text="The user that performed the action — for 'Sara mentioned you' rows.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actor_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('system', 'System'), ('billing', 'Billing'), ('mention', 'Mention'), ('comment', 'Comment'), ('security', 'Security')], default='system', help_text='Drives preference matching + filter pills on the list page.', max_length=16),
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('invoice_sent', 'Invoice sent'), ('invoice_paid', 'Invoice paid'), ('invoice_void', 'Invoice voided'), ('order_placed', 'Order placed'), ('new_mail', 'New mail'), ('new_chat', 'New chat message'), ('mention', 'Mention'), ('comment', 'Comment'), ('security', 'Security')], max_length=32),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'archived_at'], name='notificatio_recipie_0efef1_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'category', '-created_at'], name='notificatio_recipie_7b1202_idx'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pushsubscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='notificationpreference',
            index=models.Index(fields=['user', 'category'], name='notificatio_user_id_e0a7cc_idx'),
        ),
        migrations.AddConstraint(
            model_name='notificationpreference',
            constraint=models.UniqueConstraint(fields=('user', 'category'), name='uniq_notificationpreference_per_user_per_category'),
        ),
        migrations.AddIndex(
            model_name='pushsubscription',
            index=models.Index(fields=['user'], name='notificatio_user_id_d7f78b_idx'),
        ),
    ]
